### ISSUE TITLE
Interesting Use of Try/Except Statement 

### ISSUE THREAD

**Issue by shohtime** [jwkeepers/pwp-capstones#1]
https://github.com/jwkeepers/pwp-capstones/blob/ae45536f039400bbd6f29cda963ba7c08ba41179/JoeKeepers_murder_mystery_program/murder_mystery_finished.ipynb#L143-L146

This is an interesting use of a try/except statement to access a dictionary's values. Although I must admit that it's clever, I can't say I'm a fan. Beyond the scope of this course, you learn that a try/except statement is relatively costly in terms of efficiency compared to a simple if statement, especially when an exception is actually raised (as it is in this case many times). You should save such a statement for when it is necessary, and instead use built-in functions for dictionaries, such as .get() here.

**Comment by jwkeepers** [comment]
Thank you for your comments, so noted.
